name: KitPro
main: KitPro\KitPro
version: "4.1"
api: 1.10.0
author: Glitchmaster-PE

commands:
  kitpro:
    description: Choose a kit
    usage: "/kitpro <kit name> or /kitpro list"
    permission: kitpro.kit
  donator:
    description: Make a user a donator
    usage: "/donator <add|rmv> <exact username>"
    permission: kitpro.donator
    
permissions:
  kitpro.kit:
    default: true
  kitpro.donator:
    default: true
